[package]
name = "sudoku"
version = "0.1.0"
authors = ["Sam Myers <sam@sam-myers.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.clap]
version = "2.33.2"
features = [ "suggestions", "color" ]
